#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2_AR72614 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Feb 23 21:24:38 PST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_edge_detectors_behav -key {Behavioral:sim_1:Functional:tb_edge_detectors} -tclbatch tb_edge_detectors.tcl -log simulate.log"
xsim tb_edge_detectors_behav -key {Behavioral:sim_1:Functional:tb_edge_detectors} -tclbatch tb_edge_detectors.tcl -log simulate.log

